js hw
wonderfulLU/js_course pull request #1
Opened 2023-05-01 10:29 UTC by wonderfulLU

my hw

2023-05-03 11:42 UTC, SanitarskyiDmytro requested changes

2023-05-03 11:42 UTC, SanitarskyiDmytro commented on js_hw/HW27.04.js
> +    let metr = 4990;
це не зовсім те що потрібно було) але правильно)

2023-05-03 11:42 UTC, SanitarskyiDmytro commented on js_hw/HW27.04.js
> +    let metr = 999;
це те що потрібно було, але не всі кейси охопили.
let metr = 101; видає неправильний результат

2023-05-10 22:18 UTC, closed without merging

2023-05-10 22:18 UTC, wonderfulLU commented
smt